name: "unit test"

on: push

jobs:
  build:
    strategy:
      matrix:
        node: [10, 12, 14]
        webpack: [3, 4, 5]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: bin/ci-install.sh
        env:
          NODE_AUTH_TOKEN: ${{ matrix.webpack }}
      - run: npm test